### PR TITLE
Use single timeout for game timer

### PR DESCRIPTION
**Pull request by uesteibar**
Now the animation for the top timer bar is done through css. This way,
we avoid adding callbacks into the event-loop, thus ending up with a
more accurate timer and better performance.

### CODE REVIEW

**Comment by uesteibar** [comment]
You can try it out at https://deploy-preview-8--frutinder.netlify.com/

**Review by xsimov — APPROVED** [review]
Nice trick! 🎩

**Review by tebs — APPROVED** [review]
This will probably solved the ugly UI issue we have in some devices. Would be nice to test this version with someone that reported the error.

**Comment by uesteibar** [comment]
@tebs lets merge it and find someone that reported the issue to try it out 👍

**Pull request merged**
