### PR TITLE
Clarify game mechanics

### LINKED ISSUE #4: Game mechanic is not clear
If a user is not familiar with the tinder-like card interaction, they won't know what to do when being presented with a pile of cards.

 Show how to interact with a little animation (or a text if that's easier). We could do it:
1) **before** starting the game.
2) **during** the game **below** the cards.
2) **during** the game **above** the cards.

imho, the simplest and most effective would be to show a text like
> Arrastra la fruta a la derecha si piensas que sí o a la izquierda si piensas que no

for the first couple of interactions right below the _¿Estoy de temporada?_ text.

What do you think?

### PR DESCRIPTION
**Pull request by uesteibar**
Fixes #4

Not sure if the layout is nice like this, feel free to propose adjustments :)

You can try it out on https://deploy-preview-11--frutinder.netlify.com/

Screenshot 2019-08-23 at 17 34 20

### CODE REVIEW

**Comment by uesteibar** [comment]
BTW, we tested this on the weekend with a user that was getting the flickering bug issue on frutinder.com and it didn't happen with this branch, so hopefully this fixes it 🤞 (still no clue why it happened though)

**Review by dsantosmerino — APPROVED** [review]
🤟🤟

**Review by xsimov — APPROVED** [review]

**Comment by tebs** [comment]
I would put the instructions on a separate screen. It's too much text and people don't read it (our test user didn't read it 🤓 ) or when they finish reading it and finally understand it they have run out of time and it's a bit frustrating. 

My 2 cents (sorry for replying this late 🙈 )

**Comment by uesteibar** [comment]
@tebs I do like it better that way, I'll do the change

**Comment by uesteibar** [comment]
@tebs @xsimov @dsantosmerino how do you folks feel about this?

frutinder-instructions

Would you change something in the copy?
Same as before, you can try it out on https://deploy-preview-11--frutinder.netlify.com

**Comment by tebs** [comment]
Screenshot 2019-09-01 at 19 13 55

wdyt?

**Comment by uesteibar** [comment]
@tebs I have applied those copies, it reads much better now!

**Review by tebs — APPROVED** [review]

**Comment by uesteibar** [comment]
@xsimov @dsantosmerino would you be so kind to please have another look here and see if you folks like the solution? 😃

**Review by dsantosmerino — APPROVED** [review]

**Comment by uesteibar** [comment]
I'm merging this and we can iterate afterwards 😄 🚀 🌔 🌵

**Comment by xsimov** [comment]
I am late to the party, but I love the changes! Awesome!! 💯

**Pull request merged**
